spring:
  application:
    name: email-sender
  datasource:
    url: jdbc:postgresql://localhost:5432/email-sender
    username: postgres
    password: root
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true

naudo:
  config:
    username: noreply.naudo@gmail.com
    password: cocjtlhdnioifbqs

server:
  port: 8822
  
  
  
