spring:
  application:
    name: email-sender
  mail:
    host: smtp.gmail.com
    port: 587
    username: naudodev@gmail.com
    password: 
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8822
  
