spring:
  application:
    name: email-sender
  mail:
    host: smtp.gmail.com
    port: 587
    username: naudodev@gmail.com
    password: 
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8822
  
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka      
